### PR TITLE
fix: use default value for option when `undefined` is passed

### LINKED ISSUE #290: Passing option with `undefined` does not use default value for option
### Description

If I set `store` to `undefined`, I expect the library to use the default `MemoryStore`. Instead, it treats `undefined` as the store.

Related to #289.

### Library version

6.1.0

### Node version

Any version

### Typescript version (if you are using it)

Any version

### Module system

Any module system

### PR DESCRIPTION
**Pull request by zkldi**
## Related Issues

Closes #290

## What Does This PR Do?

This PR changes how options are merged with the defaults. At the moment, passing
```js
{ windowMs: undefined }
```

as an option, will result in `windowMs` being set to undefined, rather than falling back to the default of `60000ms`. This is a bit counterintuitive, as most APIs in JS do not differentiate between a property not existing and a property being undefined. This is a consequence of the spread operator being used, though.

### Added

Added a new private function that omits the options, and is called inside `parseOptions`.

## Caveats/Problems/Issues

TypeScript **really** sucks at dealing with object mutation like this. I have had to add a `@ts-expect-error` and `eslint-disable-next-line` inside the function that mutates the object. I spent about 15 minutes trying to come up with a neater way to mutate the object that didn't require this, but I couldn't figure it out.

I ran `autofix`, so that should make this code fit in with the repo a bit better.q

## Checklist

- [X] The issues that this PR fixes/closes have been mentioned above.
- [X] What this PR adds/changes/removes has been explained.
- [X] All tests (`npm test`) pass.
- [X] All added/modified code has been commented, and
      methods/classes/constants/types have been annotated with TSDoc comments.
- [X] If a new feature has been added or a bug has been fixed, tests have been
      added for the same.

### CODE REVIEW

**Comment by gamemaker1** [comment]
Hi @zkldi,

Thanks for the PR! It looks good at first glance, but it's really late right now - I'll review it in detail first thing tomorrow :)

**Comment by zkldi** [comment]
Thank you! appreciate your time.

File: source/lib.ts [hunk 1]
```diff
@@ -76,18 +76,23 @@ const promisifyStore = (passedStore: LegacyStore | Store): Store => {
 	return new PromisifiedStore()
 }
 
+type OptionsWithLegacyStore = Omit<Partial<Options>, 'store'> & {
+	store?: Store | LegacyStore
+}
```
Comment (gamemaker1) [inline source/lib.ts:81]: What if we made two different interfaces:

1. `Options`: this is represents the options the user can pass to the rate limiter. The `store` field in the `Options` interface should then be changed to be of type `Store | LegacyStore`. All fields should remain `readonly`, as they currently are.

2. `Configuration`: this represents the parsed configuration that we derive from the options passed. This can exclude deprecated fields like `headers` and `draft_polli_ratelimit_headers`, the `store` field should be of type `Store` and all fields can be read-write.

File: source/lib.ts [hunk 2]
```diff
@@ -76,18 +76,23 @@ const promisifyStore = (passedStore: LegacyStore | Store): Store => {
...
-const parseOptions = (
-	passedOptions: Omit<Partial<Options>, 'store'> & {
-		store?: Store | LegacyStore
-	},
-): Options => {
+const parseOptions = (passedOptions: OptionsWithLegacyStore): Options => {
+	// Passing undefined should be equivalent to not passing an option at all, so we'll
+	// omit all fields where their value is undefined.
+	const omittedOptions: OptionsWithLegacyStore =
+		omitUndefinedOptions(passedOptions)
```
Comment (gamemaker1) [inline source/lib.ts:94]: Maybe we could put the `omitUndefinedOptions` code here itself instead of declaring a new function? It is just a loop after all.

And the `ommittedOptions` variable could be of type `Partial<Options>` once we implement the change above.

Comment (gamemaker1) [reply source/lib.ts:94]: Also, could we rename `ommittedOptions` to something like `notUndefinedOptions`?

File: source/lib.ts [hunk 3]
```diff
@@ -76,18 +76,23 @@ const promisifyStore = (passedStore: LegacyStore | Store): Store => {
...
  * @param options {Options} - The options the user specifies.
  *
  * @returns {Options} - A complete configuration object.
  */
-const parseOptions = (
-	passedOptions: Omit<Partial<Options>, 'store'> & {
-		store?: Store | LegacyStore
-	},
-): Options => {
+const parseOptions = (passedOptions: OptionsWithLegacyStore): Options => {
```
Comment (gamemaker1) [inline source/lib.ts:90]: If we add the `Configuration` interface, this function should return it:

```suggestion
const parseOptions = (passedOptions: OptionsWithLegacyStore): Configuration => {
```

File: source/lib.ts [hunk 4]
```diff
@@ -76,18 +76,23 @@ const promisifyStore = (passedStore: LegacyStore | Store): Store => {
...
+type OptionsWithLegacyStore = Omit<Partial<Options>, 'store'> & {
+	store?: Store | LegacyStore
+}
+
 /**
  * Type-checks and adds the defaults for options the user has not specified.
  *
  * @param options {Options} - The options the user specifies.
  *
  * @returns {Options} - A complete configuration object.
```
Comment (gamemaker1) [inline source/lib.ts:88]:
```suggestion
 * @returns {Configuration} - A complete configuration object.
```

File: source/lib.ts [hunk 5]
```diff
@@ -76,18 +76,23 @@ const promisifyStore = (passedStore: LegacyStore | Store): Store => {
...
-): Options => {
+const parseOptions = (passedOptions: OptionsWithLegacyStore): Options => {
+	// Passing undefined should be equivalent to not passing an option at all, so we'll
+	// omit all fields where their value is undefined.
+	const omittedOptions: OptionsWithLegacyStore =
+		omitUndefinedOptions(passedOptions)
+
 	// See ./types.ts#Options for a detailed description of the options and their
 	// defaults.
 	const options = {
```
Comment (gamemaker1) [inline source/lib.ts:98]: With the new `Configuration` interface, this could be made:

```suggestion
	const config: Configuration = {
```

File: source/lib.ts [hunk 6]
```diff
@@ -126,8 +131,8 @@ const parseOptions = (
 			_response: Response,
 			_optionsUsed: Options,
 		): void => {},
-		// Allow the above to be overriden by the options passed to the middleware
-		...passedOptions,
+		// Allow the options object to be overrode by the options passed to the middleware.
```
Comment (gamemaker1) [inline source/lib.ts:134]:
```suggestion
		// Allow the default values to be overriden by the options passed to the middleware.
```

I think overriden (the past participle) fits here

**Review by gamemaker1 — COMMENTED** [review]
Suggested a couple of changes - most notably the introduction of a `Configuration` type that will enable us to get rid of the `@ts-expect-error` comments while parsing the options.

File: source/lib.ts (hunk 2 above)
Comment (zkldi) [reply source/lib.ts:99]: Renamed the variable -- however, I moved the omitting function to a separate function because it's not very clean. It's only used once so it's fine to inline, but it's not great :s

File: source/lib.ts (hunk 1 above)
Comment (zkldi) [reply source/lib.ts]: Added the Configuration type. I'm not familiar with what fields are deprecated in this library so I just omitted the ones you mentioned.

Comment (gamemaker1) [reply source/lib.ts]: If we make `Configuration` a separate interface, whose fields do not have the `readonly` modifier, we could get rid of the `@ts-expect-error` directive.

File: source/lib.ts [hunk 7]
```diff
@@ -76,87 +76,96 @@ const promisifyStore = (passedStore: LegacyStore | Store): Store => {
...
-				console.error(
-					'WARN | `express-rate-limit` | `request.ip` is undefined. You can avoid this by providing a custom `keyGenerator` function, but it may be indicative of a larger issue.',
-				)
-			}
+	const config: Omit<Configuration, 'store'> & { store: Store | LegacyStore } =
+		{
+			windowMs: 60 * 1000,
+			// It's possible that this field might have a LegacyConfig if overrode by passedOptions.
+			// However, LegacyStores are converted to Stores later.
+			store: new MemoryStore(),
```
Comment (gamemaker1) [inline source/lib.ts:108]: I don't like the `Omit` stuff we are doing [here](https://github.com/nfriedly/express-rate-limit/pull/294/files/6d2632fbc6f5f5d236e2725b4002be38d4649ce0..7eb1e6b39a2ff1dfdb92d65729bff9168f2b41aa#diff-5c2516e9822679491492c832b9ace79b6945bdd891586e07b0232ebef1c7e0b1R103) - we could remove the need for that by changing this line to:

```suggestion
			store: promisifyStore(notUndefinedOptions.store ?? new MemoryStore()),
```

And removing the `promisifyStore` call [here](https://github.com/nfriedly/express-rate-limit/pull/294/files/6d2632fbc6f5f5d236e2725b4002be38d4649ce0..7eb1e6b39a2ff1dfdb92d65729bff9168f2b41aa#diff-5c2516e9822679491492c832b9ace79b6945bdd891586e07b0232ebef1c7e0b1R165).

File: source/lib.ts [hunk 8]
```diff
@@ -100,72 +100,65 @@ const parseOptions = (passedOptions: Partial<Options>): Configuration => {
...
+		},
+		onLimitReached: (
+			_request: Request,
+			_response: Response,
+			_optionsUsed: Options,
+		): void => {},
+		// Allow the options object to be overriden by the options passed to the middleware.
+		...notUndefinedOptions,
+		// Note that this field is declared after the user's options are spread in,
+		// so that this field doesn't get overriden with an un-promisified store!
```
Comment (gamemaker1) [inline source/lib.ts:141]: Good catch 🚀

File: source/lib.ts [hunk 9]
```diff
@@ -119,39 +128,37 @@ const parseOptions = (
...
-		...passedOptions,
+		// Allow the options object to be overriden by the options passed to the middleware.
+		...notUndefinedOptions,
+		// Note that this field is declared after the user's options are spread in,
+		// so that this field doesn't get overriden with an un-promisified store!
+		store: promisifyStore(notUndefinedOptions.store ?? new MemoryStore()),
 	}
 
 	// Ensure that the store passed implements the either the `Store` or `LegacyStore`
 	// interface
```
Comment (nfriedly) [inline source/lib.ts:146]: This comment is now outdated

```suggestion
	// Ensure that the store passed implements the either the `Store` interface
```

(unless we want to move this check to earlier, so that it can validate a legacy store before it's promisified)

Comment (zkldi) [reply source/lib.ts]: Resolved

**Review by nfriedly — APPROVED** [review]
Thanks @zkldi - I really like this overall.

I se one minor point - Because the validation happens after the `promisifyStore` step here, this results in almost no validation of legacy stores... but given that any new store would likely use the new API, that's probably OK.

@gamemaker1: feel free to merge and publish once you're happy with this PR.

File: source/lib.ts (hunk 1 above)
Comment (gamemaker1) [reply source/lib.ts]: @zkldi could you implement this (create a separate interface for `Configuration`) change?

**Comment by gamemaker1** [comment]
Apart from [this](https://github.com/nfriedly/express-rate-limit/pull/294#discussion_r803259250), I think this is really great - thanks a lot @zkldi :)

Maybe in a future PR we could add some manual type checking for all the options (I'm thinking looping through the passed options and if an option is set, compare the type of the passed option with the type of the default value).

**Review by gamemaker1 — CHANGES_REQUESTED** [review]
Apart from [this](https://github.com/nfriedly/express-rate-limit/pull/294#discussion_r803259250), I think this is really great - thanks a lot @zkldi :)

**Comment by gamemaker1** [comment]
Also maybe in a future PR we could add some manual type checking for all the options (I'm thinking looping through the passed options and if an option is set, compare the type of the passed option with the type of the default value).

File: source/lib.ts (hunk 1 above)
Comment (zkldi) [reply source/lib.ts]: Sure, I take it i can just copy over the implementation from Options?

Comment (zkldi) [reply source/lib.ts]: No worries, I should have a commit up in the hour.

Comment (gamemaker1) [reply source/lib.ts]: Great, thanks a lot :D

Comment (zkldi) [reply source/lib.ts]: It seems a bit redundant to copy the implementation twice. Is there any actual reason Options is marked as readonly?

Comment (zkldi) [reply source/lib.ts]: Yuck. Changing this just gives us a different TS error -- ` Unsafe assignment of an any value.  @typescript-eslint/no-unsafe-assignment`. As mentioned before TS is pretty poor when it comes to performing object manipulation.

Changing to a Configuration type doesn't appear to let us remove the ts-expect-error directive.

Comment (gamemaker1) [reply source/lib.ts]: The `Options` interface's properties are marked readonly to ensure we don't change them anyhow - see issue #132

Comment (gamemaker1) [reply source/lib.ts]: The error you describe is a linter error, and you can suppress that separately. I usually try to suppress only lint errors if I have to, not compiler errors.

Comment (zkldi) [reply source/lib.ts]: Oh yeah whoops - my bad. I'll submit the commit now then.

**Review by gamemaker1 — APPROVED** [review]
LGTM! Merging, and will release a new version soon.

Thanks for the great work @zkldi

**Comment by zkldi** [comment]
Thank you!

**Comment by gamemaker1** [comment]
Released as part of [`v6.2.1`](https://github.com/nfriedly/express-rate-limit/releases/tag/v6.2.1) 🎉
